<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PsgcSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('psgc_barangays')->delete();
        DB::table('psgc_cities')->delete();
        DB::table('psgc_provinces')->delete();

        $provinces = $this->provinces();
        DB::table('psgc_provinces')->insert($provinces);

        $cities = [];
        foreach ($this->citiesByProvince() as $provinceCode => $list) {
            foreach ($list as [$name, $class]) {
                $slug = strtoupper(preg_replace('/[^A-Za-z0-9]+/', '_', $name));
                $cities[] = [
                    'code'          => $provinceCode . '-' . $slug,
                    'name'          => $name,
                    'province_code' => $provinceCode,
                    'city_class'    => $class,
                ];
            }
        }
        foreach (array_chunk($cities, 200) as $chunk) {
            DB::table('psgc_cities')->insert($chunk);
        }
    }

    private function provinces(): array
    {
        return [
            // CAR
            ['code'=>'ABR',  'name'=>'Abra',               'region_code'=>'CAR','region_name'=>'Cordillera Administrative Region'],
            ['code'=>'APA',  'name'=>'Apayao',              'region_code'=>'CAR','region_name'=>'Cordillera Administrative Region'],
            ['code'=>'BNG',  'name'=>'Benguet',             'region_code'=>'CAR','region_name'=>'Cordillera Administrative Region'],
            ['code'=>'IFU',  'name'=>'Ifugao',              'region_code'=>'CAR','region_name'=>'Cordillera Administrative Region'],
            ['code'=>'KAL',  'name'=>'Kalinga',             'region_code'=>'CAR','region_name'=>'Cordillera Administrative Region'],
            ['code'=>'MNP',  'name'=>'Mountain Province',   'region_code'=>'CAR','region_name'=>'Cordillera Administrative Region'],
            // NCR
            ['code'=>'NCR',  'name'=>'Metro Manila (NCR)',  'region_code'=>'NCR','region_name'=>'National Capital Region'],
            // Region I
            ['code'=>'INO',  'name'=>'Ilocos Norte',        'region_code'=>'I',  'region_name'=>'Ilocos Region'],
            ['code'=>'ISU',  'name'=>'Ilocos Sur',          'region_code'=>'I',  'region_name'=>'Ilocos Region'],
            ['code'=>'LUN',  'name'=>'La Union',            'region_code'=>'I',  'region_name'=>'Ilocos Region'],
            ['code'=>'PGS',  'name'=>'Pangasinan',          'region_code'=>'I',  'region_name'=>'Ilocos Region'],
            // Region II
            ['code'=>'BTN',  'name'=>'Batanes',             'region_code'=>'II', 'region_name'=>'Cagayan Valley'],
            ['code'=>'CAG',  'name'=>'Cagayan',             'region_code'=>'II', 'region_name'=>'Cagayan Valley'],
            ['code'=>'ISA',  'name'=>'Isabela',             'region_code'=>'II', 'region_name'=>'Cagayan Valley'],
            ['code'=>'NVZ',  'name'=>'Nueva Vizcaya',       'region_code'=>'II', 'region_name'=>'Cagayan Valley'],
            ['code'=>'QUI',  'name'=>'Quirino',             'region_code'=>'II', 'region_name'=>'Cagayan Valley'],
            // Region III
            ['code'=>'AUR',  'name'=>'Aurora',              'region_code'=>'III','region_name'=>'Central Luzon'],
            ['code'=>'BAT',  'name'=>'Bataan',              'region_code'=>'III','region_name'=>'Central Luzon'],
            ['code'=>'BUL',  'name'=>'Bulacan',             'region_code'=>'III','region_name'=>'Central Luzon'],
            ['code'=>'NEC',  'name'=>'Nueva Ecija',         'region_code'=>'III','region_name'=>'Central Luzon'],
            ['code'=>'PAM',  'name'=>'Pampanga',            'region_code'=>'III','region_name'=>'Central Luzon'],
            ['code'=>'TAR',  'name'=>'Tarlac',              'region_code'=>'III','region_name'=>'Central Luzon'],
            ['code'=>'ZMB',  'name'=>'Zambales',            'region_code'=>'III','region_name'=>'Central Luzon'],
            // Region IV-A CALABARZON
            ['code'=>'BTG',  'name'=>'Batangas',            'region_code'=>'IVA','region_name'=>'CALABARZON'],
            ['code'=>'CAV',  'name'=>'Cavite',              'region_code'=>'IVA','region_name'=>'CALABARZON'],
            ['code'=>'LAG',  'name'=>'Laguna',              'region_code'=>'IVA','region_name'=>'CALABARZON'],
            ['code'=>'QUE',  'name'=>'Quezon',              'region_code'=>'IVA','region_name'=>'CALABARZON'],
            ['code'=>'RIZ',  'name'=>'Rizal',               'region_code'=>'IVA','region_name'=>'CALABARZON'],
            // Region IV-B MIMAROPA
            ['code'=>'MAR',  'name'=>'Marinduque',          'region_code'=>'IVB','region_name'=>'MIMAROPA'],
            ['code'=>'OCC',  'name'=>'Occidental Mindoro',  'region_code'=>'IVB','region_name'=>'MIMAROPA'],
            ['code'=>'ORI',  'name'=>'Oriental Mindoro',    'region_code'=>'IVB','region_name'=>'MIMAROPA'],
            ['code'=>'PAL',  'name'=>'Palawan',             'region_code'=>'IVB','region_name'=>'MIMAROPA'],
            ['code'=>'ROM',  'name'=>'Romblon',             'region_code'=>'IVB','region_name'=>'MIMAROPA'],
            // Region V Bicol
            ['code'=>'ALB',  'name'=>'Albay',               'region_code'=>'V',  'region_name'=>'Bicol Region'],
            ['code'=>'CNO',  'name'=>'Camarines Norte',     'region_code'=>'V',  'region_name'=>'Bicol Region'],
            ['code'=>'CSU',  'name'=>'Camarines Sur',       'region_code'=>'V',  'region_name'=>'Bicol Region'],
            ['code'=>'CTA',  'name'=>'Catanduanes',         'region_code'=>'V',  'region_name'=>'Bicol Region'],
            ['code'=>'MSB',  'name'=>'Masbate',             'region_code'=>'V',  'region_name'=>'Bicol Region'],
            ['code'=>'SOR',  'name'=>'Sorsogon',            'region_code'=>'V',  'region_name'=>'Bicol Region'],
            // Region VI Western Visayas
            ['code'=>'AKL',  'name'=>'Aklan',               'region_code'=>'VI', 'region_name'=>'Western Visayas'],
            ['code'=>'ANT',  'name'=>'Antique',             'region_code'=>'VI', 'region_name'=>'Western Visayas'],
            ['code'=>'CAP',  'name'=>'Capiz',               'region_code'=>'VI', 'region_name'=>'Western Visayas'],
            ['code'=>'GUI',  'name'=>'Guimaras',            'region_code'=>'VI', 'region_name'=>'Western Visayas'],
            ['code'=>'ILO',  'name'=>'Iloilo',              'region_code'=>'VI', 'region_name'=>'Western Visayas'],
            ['code'=>'NOC',  'name'=>'Negros Occidental',   'region_code'=>'VI', 'region_name'=>'Western Visayas'],
            // Region VII Central Visayas
            ['code'=>'BOH',  'name'=>'Bohol',               'region_code'=>'VII','region_name'=>'Central Visayas'],
            ['code'=>'CEB',  'name'=>'Cebu',                'region_code'=>'VII','region_name'=>'Central Visayas'],
            ['code'=>'NOR',  'name'=>'Negros Oriental',     'region_code'=>'VII','region_name'=>'Central Visayas'],
            ['code'=>'SIQ',  'name'=>'Siquijor',            'region_code'=>'VII','region_name'=>'Central Visayas'],
            // Region VIII Eastern Visayas
            ['code'=>'BIL',  'name'=>'Biliran',             'region_code'=>'VIII','region_name'=>'Eastern Visayas'],
            ['code'=>'EAS',  'name'=>'Eastern Samar',       'region_code'=>'VIII','region_name'=>'Eastern Visayas'],
            ['code'=>'LEY',  'name'=>'Leyte',               'region_code'=>'VIII','region_name'=>'Eastern Visayas'],
            ['code'=>'NSA',  'name'=>'Northern Samar',      'region_code'=>'VIII','region_name'=>'Eastern Visayas'],
            ['code'=>'SAM',  'name'=>'Samar (Western Samar)','region_code'=>'VIII','region_name'=>'Eastern Visayas'],
            ['code'=>'SLE',  'name'=>'Southern Leyte',      'region_code'=>'VIII','region_name'=>'Eastern Visayas'],
            // Region IX Zamboanga Peninsula
            ['code'=>'ZDN',  'name'=>'Zamboanga del Norte', 'region_code'=>'IX', 'region_name'=>'Zamboanga Peninsula'],
            ['code'=>'ZDS',  'name'=>'Zamboanga del Sur',   'region_code'=>'IX', 'region_name'=>'Zamboanga Peninsula'],
            ['code'=>'ZSI',  'name'=>'Zamboanga Sibugay',   'region_code'=>'IX', 'region_name'=>'Zamboanga Peninsula'],
            // Region X Northern Mindanao
            ['code'=>'BUK',  'name'=>'Bukidnon',            'region_code'=>'X',  'region_name'=>'Northern Mindanao'],
            ['code'=>'CAI',  'name'=>'Camiguin',            'region_code'=>'X',  'region_name'=>'Northern Mindanao'],
            ['code'=>'LDN',  'name'=>'Lanao del Norte',     'region_code'=>'X',  'region_name'=>'Northern Mindanao'],
            ['code'=>'MOC',  'name'=>'Misamis Occidental',  'region_code'=>'X',  'region_name'=>'Northern Mindanao'],
            ['code'=>'MOR',  'name'=>'Misamis Oriental',    'region_code'=>'X',  'region_name'=>'Northern Mindanao'],
            // Region XI Davao Region
            ['code'=>'COM',  'name'=>'Davao de Oro',        'region_code'=>'XI', 'region_name'=>'Davao Region'],
            ['code'=>'DVN',  'name'=>'Davao del Norte',     'region_code'=>'XI', 'region_name'=>'Davao Region'],
            ['code'=>'DVS',  'name'=>'Davao del Sur',       'region_code'=>'XI', 'region_name'=>'Davao Region'],
            ['code'=>'DVO',  'name'=>'Davao Occidental',    'region_code'=>'XI', 'region_name'=>'Davao Region'],
            ['code'=>'DOR',  'name'=>'Davao Oriental',      'region_code'=>'XI', 'region_name'=>'Davao Region'],
            // Region XII SOCCSKSARGEN
            ['code'=>'NCO',  'name'=>'Cotabato (North Cotabato)','region_code'=>'XII','region_name'=>'SOCCSKSARGEN'],
            ['code'=>'SAR',  'name'=>'Sarangani',           'region_code'=>'XII','region_name'=>'SOCCSKSARGEN'],
            ['code'=>'SCO',  'name'=>'South Cotabato',      'region_code'=>'XII','region_name'=>'SOCCSKSARGEN'],
            ['code'=>'SKU',  'name'=>'Sultan Kudarat',      'region_code'=>'XII','region_name'=>'SOCCSKSARGEN'],
            // Region XIII CARAGA
            ['code'=>'AGN',  'name'=>'Agusan del Norte',    'region_code'=>'XIII','region_name'=>'CARAGA'],
            ['code'=>'AGS',  'name'=>'Agusan del Sur',      'region_code'=>'XIII','region_name'=>'CARAGA'],
            ['code'=>'DIN',  'name'=>'Dinagat Islands',     'region_code'=>'XIII','region_name'=>'CARAGA'],
            ['code'=>'SUN',  'name'=>'Surigao del Norte',   'region_code'=>'XIII','region_name'=>'CARAGA'],
            ['code'=>'SUS',  'name'=>'Surigao del Sur',     'region_code'=>'XIII','region_name'=>'CARAGA'],
            // BARMM
            ['code'=>'BAS',  'name'=>'Basilan',             'region_code'=>'BARMM','region_name'=>'Bangsamoro Autonomous Region in Muslim Mindanao'],
            ['code'=>'LDS',  'name'=>'Lanao del Sur',       'region_code'=>'BARMM','region_name'=>'Bangsamoro Autonomous Region in Muslim Mindanao'],
            ['code'=>'MGN',  'name'=>'Maguindanao del Norte','region_code'=>'BARMM','region_name'=>'Bangsamoro Autonomous Region in Muslim Mindanao'],
            ['code'=>'MGS',  'name'=>'Maguindanao del Sur', 'region_code'=>'BARMM','region_name'=>'Bangsamoro Autonomous Region in Muslim Mindanao'],
            ['code'=>'SUL',  'name'=>'Sulu',                'region_code'=>'BARMM','region_name'=>'Bangsamoro Autonomous Region in Muslim Mindanao'],
            ['code'=>'TAW',  'name'=>'Tawi-Tawi',           'region_code'=>'BARMM','region_name'=>'Bangsamoro Autonomous Region in Muslim Mindanao'],
        ];
    }

    // Each entry: [name, class] where class = City | Municipality | Component City
    private function citiesByProvince(): array
    {
        return [
            'ABR' => [
                ['Bangued','City'],['Boliney','Municipality'],['Bucay','Municipality'],
                ['Bucloc','Municipality'],['Daguioman','Municipality'],['Danglas','Municipality'],
                ['Dolores','Municipality'],['La Paz','Municipality'],['Lagayan','Municipality'],
                ['Langiden','Municipality'],['Licuan-Baay','Municipality'],['Luba','Municipality'],
                ['Malibcong','Municipality'],['Manabo','Municipality'],['Peñarrubia','Municipality'],
                ['Pidigan','Municipality'],['Pilar','Municipality'],['Sallapadan','Municipality'],
                ['San Isidro','Municipality'],['San Juan','Municipality'],['San Quintin','Municipality'],
                ['Tayum','Municipality'],['Tineg','Municipality'],['Tubo','Municipality'],
                ['Villaviciosa','Municipality'],
            ],
            'APA' => [
                ['Calanasan','Municipality'],['Conner','Municipality'],['Flora','Municipality'],
                ['Kabugao','Municipality'],['Luna','Municipality'],['Pudtol','Municipality'],
                ['Santa Marcela','Municipality'],
            ],
            'BNG' => [
                ['Atok','Municipality'],['Baguio City','City'],['Bakun','Municipality'],
                ['Bokod','Municipality'],['Buguias','Municipality'],['Itogon','Municipality'],
                ['Kabayan','Municipality'],['Kapangan','Municipality'],['Kibungan','Municipality'],
                ['La Trinidad','Municipality'],['Mankayan','Municipality'],['Sablan','Municipality'],
                ['Tuba','Municipality'],['Tublay','Municipality'],
            ],
            'IFU' => [
                ['Aguinaldo','Municipality'],['Alfonso Lista','Municipality'],['Asipulo','Municipality'],
                ['Banaue','Municipality'],['Hingyon','Municipality'],['Hungduan','Municipality'],
                ['Kiangan','Municipality'],['Lagawe','Municipality'],['Lamut','Municipality'],
                ['Litbeng','Municipality'],['Mayoyao','Municipality'],['Tinoc','Municipality'],
            ],
            'KAL' => [
                ['Balbalan','Municipality'],['Lubuagan','Municipality'],['Pasil','Municipality'],
                ['Pinukpuk','Municipality'],['Rizal','Municipality'],['Tabuk City','City'],
                ['Tanudan','Municipality'],['Tinglayan','Municipality'],
            ],
            'MNP' => [
                ['Bauko','Municipality'],['Besao','Municipality'],['Bontoc','Municipality'],
                ['Natonin','Municipality'],['Paracelis','Municipality'],['Sabangan','Municipality'],
                ['Sadanga','Municipality'],['Tadian','Municipality'],
            ],
            'NCR' => [
                ['Caloocan City','City'],['Las Piñas City','City'],['Makati City','City'],
                ['Malabon City','City'],['Mandaluyong City','City'],['Manila','City'],
                ['Marikina City','City'],['Muntinlupa City','City'],['Navotas City','City'],
                ['Parañaque City','City'],['Pasay City','City'],['Pasig City','City'],
                ['Pateros','Municipality'],['Quezon City','City'],['San Juan City','City'],
                ['Taguig City','City'],['Valenzuela City','City'],
            ],
            'INO' => [
                ['Adams','Municipality'],['Bacarra','Municipality'],['Badoc','Municipality'],
                ['Bangui','Municipality'],['Banna','Municipality'],['Batac City','City'],
                ['Burgos','Municipality'],['Carasi','Municipality'],['Currimao','Municipality'],
                ['Dingras','Municipality'],['Dumalneg','Municipality'],['Espiritu','Municipality'],
                ['Laoag City','City'],['Marcos','Municipality'],['Nueva Era','Municipality'],
                ['Pagudpud','Municipality'],['Paoay','Municipality'],['Pasuquin','Municipality'],
                ['Piddig','Municipality'],['Pinili','Municipality'],['San Nicolas','Municipality'],
                ['Sarrat','Municipality'],['Solsona','Municipality'],['Suyo','Municipality'],
                ['Vintar','Municipality'],
            ],
            'ISU' => [
                ['Alilem','Municipality'],['Banayoyo','Municipality'],['Bantay','Municipality'],
                ['Burgos','Municipality'],['Cabugao','Municipality'],['Candon City','City'],
                ['Caoayan','Municipality'],['Cervantes','Municipality'],['Galimuyod','Municipality'],
                ['Gregorio del Pilar','Municipality'],['Lidlidda','Municipality'],['Magsingal','Municipality'],
                ['Nagbukel','Municipality'],['Narvacan','Municipality'],['Quirino','Municipality'],
                ['Salcedo','Municipality'],['San Emilio','Municipality'],['San Esteban','Municipality'],
                ['San Ildefonso','Municipality'],['San Juan','Municipality'],['San Vicente','Municipality'],
                ['Santa','Municipality'],['Santa Catalina','Municipality'],['Santa Cruz','Municipality'],
                ['Santa Lucia','Municipality'],['Santa Maria','Municipality'],['Santiago','Municipality'],
                ['Santo Domingo','Municipality'],['Sigay','Municipality'],['Sinait','Municipality'],
                ['Sugpon','Municipality'],['Suyo','Municipality'],['Tagudin','Municipality'],
                ['Vigan City','City'],
            ],
            'LUN' => [
                ['Agoo','Municipality'],['Aringay','Municipality'],['Bacnotan','Municipality'],
                ['Bagulin','Municipality'],['Balaoan','Municipality'],['Bangar','Municipality'],
                ['Bauang','Municipality'],['Burgos','Municipality'],['Caba','Municipality'],
                ['Luna','Municipality'],['Naguilian','Municipality'],['Pugo','Municipality'],
                ['Rosario','Municipality'],['San Fernando City','City'],['San Gabriel','Municipality'],
                ['San Juan','Municipality'],['Santo Tomas','Municipality'],['Santol','Municipality'],
                ['Sudipen','Municipality'],['Tubao','Municipality'],
            ],
            'PGS' => [
                ['Aguilar','Municipality'],['Alaminos City','City'],['Alcala','Municipality'],
                ['Anda','Municipality'],['Asingan','Municipality'],['Balungao','Municipality'],
                ['Bani','Municipality'],['Basista','Municipality'],['Bautista','Municipality'],
                ['Bayambang','Municipality'],['Binalonan','Municipality'],['Binmaley','Municipality'],
                ['Bolinao','Municipality'],['Bugallon','Municipality'],['Burgos','Municipality'],
                ['Calasiao','Municipality'],['Dagupan City','City'],['Dasol','Municipality'],
                ['Infanta','Municipality'],['Labrador','Municipality'],['Laoac','Municipality'],
                ['Lingayen','Municipality'],['Mabini','Municipality'],['Malasiqui','Municipality'],
                ['Manaoag','Municipality'],['Mangaldan','Municipality'],['Mangatarem','Municipality'],
                ['Mapandan','Municipality'],['Natividad','Municipality'],['Pozorrubio','Municipality'],
                ['Rosales','Municipality'],['San Carlos City','City'],['San Fabian','Municipality'],
                ['San Jacinto','Municipality'],['San Manuel','Municipality'],['San Nicolas','Municipality'],
                ['San Quintin','Municipality'],['Santa Barbara','Municipality'],['Santa Maria','Municipality'],
                ['Santo Tomas','Municipality'],['Sison','Municipality'],['Sual','Municipality'],
                ['Tayug','Municipality'],['Umingan','Municipality'],['Urbiztondo','Municipality'],
                ['Urdaneta City','City'],['Villasis','Municipality'],
            ],
            'BTN' => [
                ['Basco','Municipality'],['Itbayat','Municipality'],['Ivana','Municipality'],
                ['Mahatao','Municipality'],['Sabtang','Municipality'],['Uyugan','Municipality'],
            ],
            'CAG' => [
                ['Abulug','Municipality'],['Alcala','Municipality'],['Allacapan','Municipality'],
                ['Amulung','Municipality'],['Aparri','Municipality'],['Baggao','Municipality'],
                ['Ballesteros','Municipality'],['Buguey','Municipality'],['Calayan','Municipality'],
                ['Camalaniugan','Municipality'],['Claveria','Municipality'],['Enrile','Municipality'],
                ['Gattaran','Municipality'],['Gonzaga','Municipality'],['Iguig','Municipality'],
                ['Lal-lo','Municipality'],['Lasam','Municipality'],['Pamplona','Municipality'],
                ['Peñablanca','Municipality'],['Piat','Municipality'],['Rizal','Municipality'],
                ['Sanchez-Mira','Municipality'],['Santa Ana','Municipality'],['Santa Praxedes','Municipality'],
                ['Santa Teresita','Municipality'],['Santo Niño','Municipality'],['Solana','Municipality'],
                ['Tuao','Municipality'],['Tuguegarao City','City'],
            ],
            'ISA' => [
                ['Alicia','Municipality'],['Angadanan','Municipality'],['Aurora','Municipality'],
                ['Benito Soliven','Municipality'],['Burgos','Municipality'],['Cabagan','Municipality'],
                ['Cabatuan','Municipality'],['Cauayan City','City'],['Cordon','Municipality'],
                ['Delfin Albano','Municipality'],['Dinapigue','Municipality'],['Divilacan','Municipality'],
                ['Echague','Municipality'],['Gamu','Municipality'],['Ilagan City','City'],
                ['Jones','Municipality'],['Luna','Municipality'],['Maconacon','Municipality'],
                ['Mallig','Municipality'],['Naguilian','Municipality'],['Palanan','Municipality'],
                ['Quezon','Municipality'],['Quirino','Municipality'],['Ramon','Municipality'],
                ['Reina Mercedes','Municipality'],['Roxas','Municipality'],['San Agustin','Municipality'],
                ['San Guillermo','Municipality'],['San Isidro','Municipality'],['San Manuel','Municipality'],
                ['San Mariano','Municipality'],['San Mateo','Municipality'],['San Pablo','Municipality'],
                ['Santa Maria','Municipality'],['Santiago City','City'],['Santo Tomas','Municipality'],
                ['Tumauini','Municipality'],
            ],
            'NVZ' => [
                ['Alfonso Castañeda','Municipality'],['Ambaguio','Municipality'],['Aritao','Municipality'],
                ['Bagabag','Municipality'],['Bambang','Municipality'],['Bayombong','Municipality'],
                ['Diadi','Municipality'],['Dupax del Norte','Municipality'],['Dupax del Sur','Municipality'],
                ['Kasibu','Municipality'],['Kayapa','Municipality'],['Quezon','Municipality'],
                ['Santa Fe','Municipality'],['Solano','Municipality'],['Villaverde','Municipality'],
            ],
            'QUI' => [
                ['Aglipay','Municipality'],['Cabarroguis','Municipality'],['Diffun','Municipality'],
                ['Maddela','Municipality'],['Nagtipunan','Municipality'],['Saguday','Municipality'],
            ],
            'AUR' => [
                ['Baler','Municipality'],['Casiguran','Municipality'],['Dilasag','Municipality'],
                ['Dinalungan','Municipality'],['Dingalan','Municipality'],['Dipaculao','Municipality'],
                ['Maria Aurora','Municipality'],['San Luis','Municipality'],
            ],
            'BAT' => [
                ['Abucay','Municipality'],['Bagac','Municipality'],['Balanga City','City'],
                ['Dinalupihan','Municipality'],['Hermosa','Municipality'],['Limay','Municipality'],
                ['Mariveles','Municipality'],['Morong','Municipality'],['Orani','Municipality'],
                ['Orion','Municipality'],['Pilar','Municipality'],['Samal','Municipality'],
            ],
            'BUL' => [
                ['Angat','Municipality'],['Balagtas','Municipality'],['Baliuag','Municipality'],
                ['Bocaue','Municipality'],['Bulakan','Municipality'],['Bustos','Municipality'],
                ['Calumpit','Municipality'],['Doña Remedios Trinidad','Municipality'],['Guiguinto','Municipality'],
                ['Hagonoy','Municipality'],['Malolos City','City'],['Marilao','Municipality'],
                ['Meycauayan City','City'],['Norzagaray','Municipality'],['Obando','Municipality'],
                ['Pandi','Municipality'],['Paombong','Municipality'],['Plaridel','Municipality'],
                ['Pulilan','Municipality'],['San Ildefonso','Municipality'],['San Jose del Monte City','City'],
                ['San Miguel','Municipality'],['San Rafael','Municipality'],['Santa Maria','Municipality'],
            ],
            'NEC' => [
                ['Aliaga','Municipality'],['Bongabon','Municipality'],['Cabanatuan City','City'],
                ['Cabiao','Municipality'],['Carranglan','Municipality'],['Cuyapo','Municipality'],
                ['Gabaldon','Municipality'],['Gapan City','City'],['General Mamerto Natividad','Municipality'],
                ['General Tinio','Municipality'],['Guimba','Municipality'],['Jaen','Municipality'],
                ['Laur','Municipality'],['Licab','Municipality'],['Llanera','Municipality'],
                ['Lupao','Municipality'],['Munoz','Municipality'],['Nampicuan','Municipality'],
                ['Palayan City','City'],['Pantabangan','Municipality'],['Peñaranda','Municipality'],
                ['Quezon','Municipality'],['Rizal','Municipality'],['San Antonio','Municipality'],
                ['San Isidro','Municipality'],['San Jose City','City'],['San Leonardo','Municipality'],
                ['Santa Rosa','Municipality'],['Santo Domingo','Municipality'],['Talavera','Municipality'],
                ['Talugtug','Municipality'],['Zaragoza','Municipality'],
            ],
            'PAM' => [
                ['Angeles City','City'],['Apalit','Municipality'],['Arayat','Municipality'],
                ['Bacolor','Municipality'],['Candaba','Municipality'],['Floridablanca','Municipality'],
                ['Guagua','Municipality'],['Lubao','Municipality'],['Mabalacat City','City'],
                ['Macabebe','Municipality'],['Magalang','Municipality'],['Masantol','Municipality'],
                ['Mexico','Municipality'],['Minalin','Municipality'],['Porac','Municipality'],
                ['San Fernando City','City'],['San Luis','Municipality'],['San Simon','Municipality'],
                ['Santa Ana','Municipality'],['Santa Rita','Municipality'],['Santo Tomas','Municipality'],
                ['Sasmuan','Municipality'],
            ],
            'TAR' => [
                ['Anao','Municipality'],['Bamban','Municipality'],['Camiling','Municipality'],
                ['Capas','Municipality'],['Concepcion','Municipality'],['Gerona','Municipality'],
                ['La Paz','Municipality'],['Mayantoc','Municipality'],['Moncada','Municipality'],
                ['Paniqui','Municipality'],['Pura','Municipality'],['Ramos','Municipality'],
                ['San Clemente','Municipality'],['San Jose','Municipality'],['San Manuel','Municipality'],
                ['Santa Ignacia','Municipality'],['Tarlac City','City'],['Victoria','Municipality'],
            ],
            'ZMB' => [
                ['Botolan','Municipality'],['Cabangan','Municipality'],['Candelaria','Municipality'],
                ['Castillejos','Municipality'],['Iba','Municipality'],['Masinloc','Municipality'],
                ['Olongapo City','City'],['Palauig','Municipality'],['San Antonio','Municipality'],
                ['San Felipe','Municipality'],['San Marcelino','Municipality'],['San Narciso','Municipality'],
                ['Santa Cruz','Municipality'],['Subic','Municipality'],
            ],
            'BTG' => [
                ['Agoncillo','Municipality'],['Alitagtag','Municipality'],['Balayan','Municipality'],
                ['Balete','Municipality'],['Batangas City','City'],['Bauan','Municipality'],
                ['Calaca','Municipality'],['Calatagan','Municipality'],['Cuenca','Municipality'],
                ['Ibaan','Municipality'],['Laurel','Municipality'],['Lemery','Municipality'],
                ['Lian','Municipality'],['Lipa City','City'],['Lobo','Municipality'],
                ['Mabini','Municipality'],['Malvar','Municipality'],['Mataas na Kahoy','Municipality'],
                ['Nasugbu','Municipality'],['Padre Garcia','Municipality'],['Rosario','Municipality'],
                ['San Jose','Municipality'],['San Juan','Municipality'],['San Luis','Municipality'],
                ['San Nicolas','Municipality'],['San Pascual','Municipality'],['Santa Teresita','Municipality'],
                ['Santo Tomas','Municipality'],['Taal','Municipality'],['Talisay','Municipality'],
                ['Tanauan City','City'],['Taysan','Municipality'],['Tingloy','Municipality'],['Tuy','Municipality'],
            ],
            'CAV' => [
                ['Alfonso','Municipality'],['Amadeo','Municipality'],['Bacoor City','City'],
                ['Carmona','Municipality'],['Cavite City','City'],['Dasmariñas City','City'],
                ['General Emilio Aguinaldo','Municipality'],['General Mariano Alvarez','Municipality'],
                ['General Trias City','City'],['Imus City','City'],['Indang','Municipality'],
                ['Kawit','Municipality'],['Magallanes','Municipality'],['Maragondon','Municipality'],
                ['Mendez','Municipality'],['Naic','Municipality'],['Noveleta','Municipality'],
                ['Rosario','Municipality'],['Silang','Municipality'],['Tagaytay City','City'],
                ['Tanza','Municipality'],['Ternate','Municipality'],['Trece Martires City','City'],
            ],
            'LAG' => [
                ['Alaminos','Municipality'],['Bay','Municipality'],['Biñan City','City'],
                ['Cabuyao City','City'],['Calamba City','City'],['Cavinti','Municipality'],
                ['Famy','Municipality'],['Kalayaan','Municipality'],['Liliw','Municipality'],
                ['Los Baños','Municipality'],['Luisiana','Municipality'],['Lumban','Municipality'],
                ['Mabitac','Municipality'],['Magdalena','Municipality'],['Majayjay','Municipality'],
                ['Nagcarlan','Municipality'],['Paete','Municipality'],['Pagsanjan','Municipality'],
                ['Pakil','Municipality'],['Pangil','Municipality'],['Pila','Municipality'],
                ['Rizal','Municipality'],['San Pablo City','City'],['San Pedro City','City'],
                ['Santa Cruz','Municipality'],['Santa Maria','Municipality'],['Santa Rosa City','City'],
                ['Siniloan','Municipality'],['Victoria','Municipality'],
            ],
            'QUE' => [
                ['Agdangan','Municipality'],['Alabat','Municipality'],['Atimonan','Municipality'],
                ['Buenavista','Municipality'],['Burdeos','Municipality'],['Calauag','Municipality'],
                ['Candelaria','Municipality'],['Catanauan','Municipality'],['Dolores','Municipality'],
                ['General Luna','Municipality'],['General Nakar','Municipality'],['Guinayangan','Municipality'],
                ['Gumaca','Municipality'],['Infanta','Municipality'],['Jomalig','Municipality'],
                ['Lopez','Municipality'],['Lucban','Municipality'],['Lucena City','City'],
                ['Macalelon','Municipality'],['Mauban','Municipality'],['Mulanay','Municipality'],
                ['Padre Burgos','Municipality'],['Pagbilao','Municipality'],['Panukulan','Municipality'],
                ['Patnanungan','Municipality'],['Perez','Municipality'],['Pitogo','Municipality'],
                ['Plaridel','Municipality'],['Polillo','Municipality'],['Quezon','Municipality'],
                ['Real','Municipality'],['Sampaloc','Municipality'],['San Andres','Municipality'],
                ['San Antonio','Municipality'],['San Francisco','Municipality'],['San Narciso','Municipality'],
                ['Sariaya','Municipality'],['Tagkawayan','Municipality'],['Tayabas City','City'],
                ['Tiaong','Municipality'],['Unisan','Municipality'],
            ],
            'RIZ' => [
                ['Angono','Municipality'],['Antipolo City','City'],['Baras','Municipality'],
                ['Binangonan','Municipality'],['Cainta','Municipality'],['Cardona','Municipality'],
                ['Jala-Jala','Municipality'],['Morong','Municipality'],['Pililla','Municipality'],
                ['Rodriguez','Municipality'],['San Mateo','Municipality'],['Tanay','Municipality'],
                ['Taytay','Municipality'],['Teresa','Municipality'],
            ],
            'MAR' => [
                ['Boac','Municipality'],['Buenavista','Municipality'],['Gasan','Municipality'],
                ['Mogpog','Municipality'],['Santa Cruz','Municipality'],['Torrijos','Municipality'],
            ],
            'OCC' => [
                ['Abra de Ilog','Municipality'],['Calintaan','Municipality'],['Looc','Municipality'],
                ['Lubang','Municipality'],['Magsaysay','Municipality'],['Mamburao','Municipality'],
                ['Paluan','Municipality'],['Rizal','Municipality'],['Sablayan','Municipality'],
                ['San Jose','Municipality'],['Santa Cruz','Municipality'],
            ],
            'ORI' => [
                ['Baco','Municipality'],['Bansud','Municipality'],['Bongabong','Municipality'],
                ['Bulalacao','Municipality'],['Calapan City','City'],['Gloria','Municipality'],
                ['Mansalay','Municipality'],['Naujan','Municipality'],['Pinamalayan','Municipality'],
                ['Pola','Municipality'],['Puerto Galera','Municipality'],['Roxas','Municipality'],
                ['San Teodoro','Municipality'],['Socorro','Municipality'],['Victoria','Municipality'],
            ],
            'PAL' => [
                ['Aborlan','Municipality'],['Agutaya','Municipality'],['Araceli','Municipality'],
                ['Balabac','Municipality'],['Bataraza','Municipality'],["Brooke's Point",'Municipality'],
                ['Busuanga','Municipality'],['Cagayancillo','Municipality'],['Coron','Municipality'],
                ['Culion','Municipality'],['Dumaran','Municipality'],['El Nido','Municipality'],
                ['Española','Municipality'],['Kalayaan','Municipality'],['Linapacan','Municipality'],
                ['Magsaysay','Municipality'],['Narra','Municipality'],['Puerto Princesa City','City'],
                ['Quezon','Municipality'],['Rizal','Municipality'],['Roxas','Municipality'],
                ['San Vicente','Municipality'],['Sofronio Española','Municipality'],['Taytay','Municipality'],
            ],
            'ROM' => [
                ['Alcantara','Municipality'],['Banton','Municipality'],['Cajidiocan','Municipality'],
                ['Calatrava','Municipality'],['Concepcion','Municipality'],['Corcuera','Municipality'],
                ['Ferrol','Municipality'],['Looc','Municipality'],['Magdiwang','Municipality'],
                ['Odiongan','Municipality'],['Romblon','Municipality'],['San Agustin','Municipality'],
                ['San Andres','Municipality'],['San Fernando','Municipality'],['San Jose','Municipality'],
                ['Santa Fe','Municipality'],['Santa Maria','Municipality'],
            ],
            'ALB' => [
                ['Bacacay','Municipality'],['Camalig','Municipality'],['Daraga','Municipality'],
                ['Guinobatan','Municipality'],['Jovellar','Municipality'],['Legazpi City','City'],
                ['Libon','Municipality'],['Ligao City','City'],['Malilipot','Municipality'],
                ['Malinao','Municipality'],['Manito','Municipality'],['Oas','Municipality'],
                ['Pio Duran','Municipality'],['Polangui','Municipality'],['Rapu-Rapu','Municipality'],
                ['Santo Domingo','Municipality'],['Tabaco City','City'],['Tiwi','Municipality'],
            ],
            'CNO' => [
                ['Basud','Municipality'],['Capalonga','Municipality'],['Daet','Municipality'],
                ['Jose Panganiban','Municipality'],['Labo','Municipality'],['Mercedes','Municipality'],
                ['Paracale','Municipality'],['San Lorenzo Ruiz','Municipality'],['San Vicente','Municipality'],
                ['Santa Elena','Municipality'],['Talisay','Municipality'],['Vinzons','Municipality'],
            ],
            'CSU' => [
                ['Baao','Municipality'],['Balatan','Municipality'],['Bato','Municipality'],
                ['Bombon','Municipality'],['Buhi','Municipality'],['Bula','Municipality'],
                ['Cabusao','Municipality'],['Calabanga','Municipality'],['Camaligan','Municipality'],
                ['Canaman','Municipality'],['Caramoan','Municipality'],['Del Gallego','Municipality'],
                ['Gainza','Municipality'],['Garchitorena','Municipality'],['Goa','Municipality'],
                ['Iriga City','City'],['Lagonoy','Municipality'],['Libmanan','Municipality'],
                ['Lupi','Municipality'],['Magarao','Municipality'],['Milaor','Municipality'],
                ['Minalabac','Municipality'],['Nabua','Municipality'],['Naga City','City'],
                ['Ocampo','Municipality'],['Pamplona','Municipality'],['Pasacao','Municipality'],
                ['Pili','Municipality'],['Presentacion','Municipality'],['Ragay','Municipality'],
                ['Sagñay','Municipality'],['San Fernando','Municipality'],['San Jose','Municipality'],
                ['Sipocot','Municipality'],['Siruma','Municipality'],['Tigaon','Municipality'],
                ['Tinambac','Municipality'],
            ],
            'CTA' => [
                ['Bagamanoc','Municipality'],['Baras','Municipality'],['Bato','Municipality'],
                ['Caramoran','Municipality'],['Gigmoto','Municipality'],['Pandan','Municipality'],
                ['Panganiban','Municipality'],['San Andres','Municipality'],['San Miguel','Municipality'],
                ['Viga','Municipality'],['Virac','Municipality'],
            ],
            'MSB' => [
                ['Aroroy','Municipality'],['Baleno','Municipality'],['Balud','Municipality'],
                ['Batuan','Municipality'],['Cataingan','Municipality'],['Cawayan','Municipality'],
                ['Claveria','Municipality'],['Dimasalang','Municipality'],['Esperanza','Municipality'],
                ['Mandaon','Municipality'],['Masbate City','City'],['Milagros','Municipality'],
                ['Mobo','Municipality'],['Monreal','Municipality'],['Palanas','Municipality'],
                ['Pio V. Corpuz','Municipality'],['Placer','Municipality'],['San Fernando','Municipality'],
                ['San Jacinto','Municipality'],['San Pascual','Municipality'],['Uson','Municipality'],
            ],
            'SOR' => [
                ['Barcelona','Municipality'],['Bulan','Municipality'],['Bulusan','Municipality'],
                ['Casiguran','Municipality'],['Castilla','Municipality'],['Donsol','Municipality'],
                ['Gubat','Municipality'],['Irosin','Municipality'],['Juban','Municipality'],
                ['Magallanes','Municipality'],['Matnog','Municipality'],['Pilar','Municipality'],
                ['Prieto Diaz','Municipality'],['Santa Magdalena','Municipality'],['Sorsogon City','City'],
            ],
            'AKL' => [
                ['Altavas','Municipality'],['Balete','Municipality'],['Banga','Municipality'],
                ['Batan','Municipality'],['Buruanga','Municipality'],['Ibajay','Municipality'],
                ['Kalibo','Municipality'],['Lezo','Municipality'],['Libacao','Municipality'],
                ['Madalag','Municipality'],['Makato','Municipality'],['Malay','Municipality'],
                ['Malinao','Municipality'],['Nabas','Municipality'],['New Washington','Municipality'],
                ['Numancia','Municipality'],['Tangalan','Municipality'],
            ],
            'ANT' => [
                ['Anini-y','Municipality'],['Barbaza','Municipality'],['Belison','Municipality'],
                ['Bugasong','Municipality'],['Caluya','Municipality'],['Culasi','Municipality'],
                ['Hamtic','Municipality'],['Laua-an','Municipality'],['Libertad','Municipality'],
                ['Pandan','Municipality'],['Patnongon','Municipality'],['San Jose de Buenavista','Municipality'],
                ['San Remigio','Municipality'],['Sebaste','Municipality'],['Sibalom','Municipality'],
                ['Tibiao','Municipality'],['Tobias Fornier','Municipality'],['Valderrama','Municipality'],
            ],
            'CAP' => [
                ['Cuartero','Municipality'],['Dao','Municipality'],['Dumalag','Municipality'],
                ['Dumarao','Municipality'],['Ivisan','Municipality'],['Jamindan','Municipality'],
                ['Ma-ayon','Municipality'],['Mambusao','Municipality'],['Panay','Municipality'],
                ['Panitian','Municipality'],['Pilar','Municipality'],['Pontevedra','Municipality'],
                ['President Roxas','Municipality'],['Roxas City','City'],['Sapian','Municipality'],
                ['Sigma','Municipality'],['Tapaz','Municipality'],
            ],
            'GUI' => [
                ['Buenavista','Municipality'],['Jordan','Municipality'],['Nueva Valencia','Municipality'],
                ['San Lorenzo','Municipality'],['Sibunag','Municipality'],
            ],
            'ILO' => [
                ['Ajuy','Municipality'],['Alimodian','Municipality'],['Anilao','Municipality'],
                ['Banate','Municipality'],['Barotac Nuevo','Municipality'],['Barotac Viejo','Municipality'],
                ['Batad','Municipality'],['Bingawan','Municipality'],['Cabatuan','Municipality'],
                ['Calinog','Municipality'],['Carles','Municipality'],['Concepcion','Municipality'],
                ['Dingle','Municipality'],['Dueñas','Municipality'],['Dumangas','Municipality'],
                ['Estancia','Municipality'],['Guimbal','Municipality'],['Igbaras','Municipality'],
                ['Iloilo City','City'],['Janiuay','Municipality'],['Lambunao','Municipality'],
                ['Leganes','Municipality'],['Lemery','Municipality'],['Leon','Municipality'],
                ['Maasin','Municipality'],['Miagao','Municipality'],['Mina','Municipality'],
                ['New Lucena','Municipality'],['Oton','Municipality'],['Pavia','Municipality'],
                ['Pototan','Municipality'],['San Dionisio','Municipality'],['San Enrique','Municipality'],
                ['San Joaquin','Municipality'],['San Miguel','Municipality'],['San Rafael','Municipality'],
                ['Santa Barbara','Municipality'],['Sara','Municipality'],['Tigbauan','Municipality'],
                ['Tubungan','Municipality'],['Zarraga','Municipality'],
            ],
            'NOC' => [
                ['Bacolod City','City'],['Bago City','City'],['Binalbagan','Municipality'],
                ['Cadiz City','City'],['Calatrava','Municipality'],['Candoni','Municipality'],
                ['Cauayan','Municipality'],['Enrique B. Magalona','Municipality'],['Escalante City','City'],
                ['Himamaylan City','City'],['Hinigaran','Municipality'],['Hinoba-an','Municipality'],
                ['Ilog','Municipality'],['Isabela','Municipality'],['Kabankalan City','City'],
                ['La Carlota City','City'],['La Castellana','Municipality'],['Manapla','Municipality'],
                ['Moises Padilla','Municipality'],['Murcia','Municipality'],['Pontevedra','Municipality'],
                ['Pulupandan','Municipality'],['Sagay City','City'],['San Carlos City','City'],
                ['San Enrique','Municipality'],['Silay City','City'],['Sipalay City','City'],
                ['Talisay City','City'],['Toboso','Municipality'],['Valladolid','Municipality'],
                ['Victorias City','City'],
            ],
            'BOH' => [
                ['Alburquerque','Municipality'],['Alicia','Municipality'],['Anda','Municipality'],
                ['Antequera','Municipality'],['Baclayon','Municipality'],['Balilihan','Municipality'],
                ['Batuan','Municipality'],['Bien Unido','Municipality'],['Bilar','Municipality'],
                ['Buenavista','Municipality'],['Calape','Municipality'],['Candijay','Municipality'],
                ['Carmen','Municipality'],['Catigbian','Municipality'],['Clarin','Municipality'],
                ['Corella','Municipality'],['Cortes','Municipality'],['Dagohoy','Municipality'],
                ['Danao','Municipality'],['Dauis','Municipality'],['Dimiao','Municipality'],
                ['Duero','Municipality'],['Garcia Hernandez','Municipality'],['Getafe','Municipality'],
                ['Guindulman','Municipality'],['Inabanga','Municipality'],['Jagna','Municipality'],
                ['Lila','Municipality'],['Loay','Municipality'],['Loboc','Municipality'],
                ['Loon','Municipality'],['Mabini','Municipality'],['Maribojoc','Municipality'],
                ['Panglao','Municipality'],['Pilar','Municipality'],['Pres. Carlos P. Garcia','Municipality'],
                ['Sagbayan','Municipality'],['San Isidro','Municipality'],['San Miguel','Municipality'],
                ['Sevilla','Municipality'],['Sierra Bullones','Municipality'],['Sikatuna','Municipality'],
                ['Tagbilaran City','City'],['Talibon','Municipality'],['Trinidad','Municipality'],
                ['Tubigon','Municipality'],['Ubay','Municipality'],['Valencia','Municipality'],
            ],
            'CEB' => [
                ['Alcantara','Municipality'],['Alcoy','Municipality'],['Alegria','Municipality'],
                ['Aloguinsan','Municipality'],['Argao','Municipality'],['Asturias','Municipality'],
                ['Badian','Municipality'],['Balamban','Municipality'],['Bantayan','Municipality'],
                ['Barili','Municipality'],['Bogo City','City'],['Boljoon','Municipality'],
                ['Borbon','Municipality'],['Carcar City','City'],['Carmen','Municipality'],
                ['Catmon','Municipality'],['Cebu City','City'],['Compostela','Municipality'],
                ['Consolacion','Municipality'],['Cordova','Municipality'],['Daanbantayan','Municipality'],
                ['Dalaguete','Municipality'],['Danao City','City'],['Dumanjug','Municipality'],
                ['Ginatilan','Municipality'],['Lapu-Lapu City','City'],['Liloan','Municipality'],
                ['Madridejos','Municipality'],['Malabuyoc','Municipality'],['Mandaue City','City'],
                ['Medellin','Municipality'],['Minglanilla','Municipality'],['Moalboal','Municipality'],
                ['Naga City','City'],['Oslob','Municipality'],['Pilar','Municipality'],
                ['Pinamungajan','Municipality'],['Poro','Municipality'],['Ronda','Municipality'],
                ['Samboan','Municipality'],['San Fernando','Municipality'],['San Francisco','Municipality'],
                ['San Remigio','Municipality'],['Santa Fe','Municipality'],['Santander','Municipality'],
                ['Sibonga','Municipality'],['Sogod','Municipality'],['Tabogon','Municipality'],
                ['Tabuelan','Municipality'],['Talisay City','City'],['Toledo City','City'],
                ['Tuburan','Municipality'],['Tudela','Municipality'],
            ],
            'NOR' => [
                ['Amlan','Municipality'],['Ayungon','Municipality'],['Bacong','Municipality'],
                ['Bais City','City'],['Basay','Municipality'],['Bayawan City','City'],
                ['Bindoy','Municipality'],['Canlaon City','City'],['Dauin','Municipality'],
                ['Dumaguete City','City'],['Guihulngan City','City'],['Jimalalud','Municipality'],
                ['La Libertad','Municipality'],['Mabinay','Municipality'],['Manjuyod','Municipality'],
                ['Pamplona','Municipality'],['San Jose','Municipality'],['Santa Catalina','Municipality'],
                ['Siaton','Municipality'],['Sibulan','Municipality'],['Tanjay City','City'],
                ['Tayasan','Municipality'],['Valencia','Municipality'],['Vallehermoso','Municipality'],
                ['Zamboanguita','Municipality'],
            ],
            'SIQ' => [
                ['Enrique Villanueva','Municipality'],['Larena','Municipality'],['Lazi','Municipality'],
                ['Maria','Municipality'],['San Juan','Municipality'],['Siquijor','Municipality'],
            ],
            'BIL' => [
                ['Almeria','Municipality'],['Biliran','Municipality'],['Cabucgayan','Municipality'],
                ['Caibiran','Municipality'],['Culaba','Municipality'],['Kawayan','Municipality'],
                ['Maripipi','Municipality'],['Naval','Municipality'],
            ],
            'EAS' => [
                ['Arteche','Municipality'],['Balangiga','Municipality'],['Balangkayan','Municipality'],
                ['Borongan City','City'],['Can-avid','Municipality'],['Dolores','Municipality'],
                ['General MacArthur','Municipality'],['Giporlos','Municipality'],['Guiuan','Municipality'],
                ['Hernani','Municipality'],['Jipapad','Municipality'],['Lawaan','Municipality'],
                ['Llorente','Municipality'],['Maslog','Municipality'],['Maydolong','Municipality'],
                ['Mercedes','Municipality'],['Oras','Municipality'],['Quinapondan','Municipality'],
                ['Salcedo','Municipality'],['San Julian','Municipality'],['San Policarpo','Municipality'],
                ['Sulat','Municipality'],['Taft','Municipality'],
            ],
            'LEY' => [
                ['Abuyog','Municipality'],['Alangalang','Municipality'],['Albuera','Municipality'],
                ['Babatngon','Municipality'],['Baybay City','City'],['Burauen','Municipality'],
                ['Calubian','Municipality'],['Capoocan','Municipality'],['Carigara','Municipality'],
                ['Dagami','Municipality'],['Dulag','Municipality'],['Hilongos','Municipality'],
                ['Hindang','Municipality'],['Inopacan','Municipality'],['Isabel','Municipality'],
                ['Jaro','Municipality'],['Javier','Municipality'],['Julita','Municipality'],
                ['Kananga','Municipality'],['La Paz','Municipality'],['Leyte','Municipality'],
                ['Liloan','Municipality'],['Macarthur','Municipality'],['Mahaplag','Municipality'],
                ['Matag-ob','Municipality'],['Matalom','Municipality'],['Mayorga','Municipality'],
                ['Merida','Municipality'],['Ormoc City','City'],['Palo','Municipality'],
                ['Palompon','Municipality'],['Pastrana','Municipality'],['San Isidro','Municipality'],
                ['San Miguel','Municipality'],['Santa Fe','Municipality'],['Tabango','Municipality'],
                ['Tabontabon','Municipality'],['Tacloban City','City'],['Tanauan','Municipality'],
                ['Tolosa','Municipality'],['Tunga','Municipality'],['Villaba','Municipality'],
            ],
            'NSA' => [
                ['Allen','Municipality'],['Biri','Municipality'],['Bobon','Municipality'],
                ['Capul','Municipality'],['Catarman','Municipality'],['Catubig','Municipality'],
                ['Gamay','Municipality'],['Lapinig','Municipality'],['Las Navas','Municipality'],
                ['Lavezares','Municipality'],['Lope de Vega','Municipality'],['Mapanas','Municipality'],
                ['Mondragon','Municipality'],['Palapag','Municipality'],['Pambujan','Municipality'],
                ['Rosario','Municipality'],['San Antonio','Municipality'],['San Isidro','Municipality'],
                ['San Jose','Municipality'],['San Roque','Municipality'],['San Vicente','Municipality'],
                ['Silvino Lobos','Municipality'],['Victoria','Municipality'],
            ],
            'SAM' => [
                ['Almagro','Municipality'],['Basey','Municipality'],['Calbayog City','City'],
                ['Calbiga','Municipality'],['Catbalogan City','City'],['Daram','Municipality'],
                ['Gandara','Municipality'],['Hinabangan','Municipality'],['Jiabong','Municipality'],
                ['Langkag','Municipality'],['Marabut','Municipality'],['Matuguinao','Municipality'],
                ['Motiong','Municipality'],['Pagsanghan','Municipality'],['Paranas','Municipality'],
                ['Pinabacdao','Municipality'],['San Jorge','Municipality'],['San Jose de Buan','Municipality'],
                ['San Sebastian','Municipality'],['Santa Margarita','Municipality'],['Santa Rita','Municipality'],
                ['Santo Niño','Municipality'],['Talalora','Municipality'],['Tarangnan','Municipality'],
                ['Villareal','Municipality'],['Zumarraga','Municipality'],
            ],
            'SLE' => [
                ['Anahawan','Municipality'],['Bontoc','Municipality'],['Hinunangan','Municipality'],
                ['Hinundayan','Municipality'],['Libagon','Municipality'],['Liloan','Municipality'],
                ['Limasawa','Municipality'],['Maasin City','City'],['Macrohon','Municipality'],
                ['Malitbog','Municipality'],['Padre Burgos','Municipality'],['Pintuyan','Municipality'],
                ['Saint Bernard','Municipality'],['San Francisco','Municipality'],['San Juan','Municipality'],
                ['San Ricardo','Municipality'],['Silago','Municipality'],['Sogod','Municipality'],
                ['Tomas Oppus','Municipality'],
            ],
            'ZDN' => [
                ['Baliguian','Municipality'],['Dapitan City','City'],['Dipolog City','City'],
                ['Godod','Municipality'],['Gutalac','Municipality'],['Jose Dalman','Municipality'],
                ['Kalawit','Municipality'],['Katipunan','Municipality'],['La Libertad','Municipality'],
                ['Labason','Municipality'],['Leon B. Postigo','Municipality'],['Liloy','Municipality'],
                ['Manukan','Municipality'],['Mutia','Municipality'],['Piñan','Municipality'],
                ['Polanco','Municipality'],['President Manuel A. Roxas','Municipality'],
                ['Rizal','Municipality'],['Salug','Municipality'],['San Jose','Municipality'],
                ['San Miguel','Municipality'],['Sergio Osmeña Sr.','Municipality'],['Siayan','Municipality'],
                ['Sibuco','Municipality'],['Sibutad','Municipality'],['Sindangan','Municipality'],
                ['Siocon','Municipality'],['Sirawai','Municipality'],['Tampilisan','Municipality'],
            ],
            'ZDS' => [
                ['Aurora','Municipality'],['Bayog','Municipality'],['Dimataling','Municipality'],
                ['Dinas','Municipality'],['Dumalinao','Municipality'],['Dumingag','Municipality'],
                ['Guipos','Municipality'],['Josefina','Municipality'],['Kumalarang','Municipality'],
                ['Labangan','Municipality'],['Lakewood','Municipality'],['Lapuyan','Municipality'],
                ['Mahayag','Municipality'],['Margosatubig','Municipality'],['Midsalip','Municipality'],
                ['Molave','Municipality'],['Pagadian City','City'],['Ramon Magsaysay','Municipality'],
                ['San Miguel','Municipality'],['San Pablo','Municipality'],['Sominot','Municipality'],
                ['Tabina','Municipality'],['Tambulig','Municipality'],['Tukuran','Municipality'],
                ['Vincenzo Sagun','Municipality'],['Zamboanga City','City'],
            ],
            'ZSI' => [
                ['Alicia','Municipality'],['Buug','Municipality'],['Diplahan','Municipality'],
                ['Imelda','Municipality'],['Ipil','Municipality'],['Kabasalan','Municipality'],
                ['Mabuhay','Municipality'],['Malangas','Municipality'],['Naga','Municipality'],
                ['Olutanga','Municipality'],['Payao','Municipality'],['Roseller T. Lim','Municipality'],
                ['Siay','Municipality'],['Talusan','Municipality'],['Titay','Municipality'],
                ['Tungawan','Municipality'],
            ],
            'BUK' => [
                ['Baungon','Municipality'],['Cabanglasan','Municipality'],['Damulog','Municipality'],
                ['Dangcagan','Municipality'],['Don Carlos','Municipality'],['Impasug-ong','Municipality'],
                ['Kadingilan','Municipality'],['Kalilangan','Municipality'],['Kibawe','Municipality'],
                ['Kitaotao','Municipality'],['Lantapan','Municipality'],['Libona','Municipality'],
                ['Malaybalay City','City'],['Malitbog','Municipality'],['Manolo Fortich','Municipality'],
                ['Maramag','Municipality'],['Pangantucan','Municipality'],['Quezon','Municipality'],
                ['San Fernando','Municipality'],['Sumilao','Municipality'],['Talakag','Municipality'],
                ['Valencia City','City'],
            ],
            'CAI' => [
                ['Catarman','Municipality'],['Guinsiliban','Municipality'],['Mahinog','Municipality'],
                ['Mambajao','Municipality'],['Sagay','Municipality'],
            ],
            'LDN' => [
                ['Bacolod','Municipality'],['Baloi','Municipality'],['Baroy','Municipality'],
                ['Iligan City','City'],['Kapatagan','Municipality'],['Kauswagan','Municipality'],
                ['Kolambugan','Municipality'],['Lala','Municipality'],['Linamon','Municipality'],
                ['Magsaysay','Municipality'],['Maigo','Municipality'],['Matungao','Municipality'],
                ['Munai','Municipality'],['Nunungan','Municipality'],['Pantao Ragat','Municipality'],
                ['Pantar','Municipality'],['Poona Piagapo','Municipality'],['Salvador','Municipality'],
                ['Sapad','Municipality'],['Sultan Naga Dimaporo','Municipality'],['Tangcal','Municipality'],
                ['Tubod','Municipality'],
            ],
            'MOC' => [
                ['Aloran','Municipality'],['Baliangao','Municipality'],['Bonifacio','Municipality'],
                ['Calamba','Municipality'],['Clarin','Municipality'],['Concepcion','Municipality'],
                ['Don Victoriano Chiongbian','Municipality'],['Jimenez','Municipality'],
                ['Lopez Jaena','Municipality'],['Oroquieta City','City'],['Ozamiz City','City'],
                ['Panaon','Municipality'],['Plaridel','Municipality'],['Sapang Dalaga','Municipality'],
                ['Sinacaban','Municipality'],['Tangub City','City'],['Tudela','Municipality'],
            ],
            'MOR' => [
                ['Alubijid','Municipality'],['Balingasag','Municipality'],['Balingoan','Municipality'],
                ['Binuangan','Municipality'],['Cagayan de Oro City','City'],['Catarman','Municipality'],
                ['Gitagum','Municipality'],['Initao','Municipality'],['Jasaan','Municipality'],
                ['Kinoguitan','Municipality'],['Lagonglong','Municipality'],['Laguindingan','Municipality'],
                ['Libertad','Municipality'],['Lugait','Municipality'],['Magsaysay','Municipality'],
                ['Manticao','Municipality'],['Medina','Municipality'],['Naawan','Municipality'],
                ['Opol','Municipality'],['Salay','Municipality'],['Sugbongcogon','Municipality'],
                ['Tagoloan','Municipality'],['Talisayan','Municipality'],['Villanueva','Municipality'],
            ],
            'COM' => [
                ['Compostela','Municipality'],['Laak','Municipality'],['Mabini','Municipality'],
                ['Maco','Municipality'],['Maragusan','Municipality'],['Mawab','Municipality'],
                ['Monkayo','Municipality'],['Montevista','Municipality'],['Nabunturan','Municipality'],
                ['New Bataan','Municipality'],['Pantukan','Municipality'],
            ],
            'DVN' => [
                ['Asuncion','Municipality'],['Braulio E. Dujali','Municipality'],['Carmen','Municipality'],
                ['Kapalong','Municipality'],['New Corella','Municipality'],['Panabo City','City'],
                ['Samal','Municipality'],['San Isidro','Municipality'],['Santo Tomas','Municipality'],
                ['Tagum City','City'],['Talaingod','Municipality'],
            ],
            'DVS' => [
                ['Bansalan','Municipality'],['Davao City','City'],['Digos City','City'],
                ['Don Marcelino','Municipality'],['Hagonoy','Municipality'],['Kiblawan','Municipality'],
                ['Magsaysay','Municipality'],['Malalag','Municipality'],['Matanao','Municipality'],
                ['Padada','Municipality'],['Santa Cruz','Municipality'],['Sulop','Municipality'],
            ],
            'DVO' => [
                ['Don Marcelino','Municipality'],['Jose Abad Santos','Municipality'],['Malita','Municipality'],
                ['Santa Maria','Municipality'],['Sarangani','Municipality'],
            ],
            'DOR' => [
                ['Baganga','Municipality'],['Banaybanay','Municipality'],['Boston','Municipality'],
                ['Caraga','Municipality'],['Cateel','Municipality'],['Governor Generoso','Municipality'],
                ['Lupon','Municipality'],['Manay','Municipality'],['Mati City','City'],
                ['San Isidro','Municipality'],['Tarragona','Municipality'],
            ],
            'NCO' => [
                ['Alamada','Municipality'],['Antipas','Municipality'],['Arakan','Municipality'],
                ['Banisilan','Municipality'],['Carmen','Municipality'],['Kabacan','Municipality'],
                ['Kidapawan City','City'],['Libungan','Municipality'],["M'lang",'Municipality'],
                ['Magpet','Municipality'],['Makilala','Municipality'],['Matalam','Municipality'],
                ['Midsayap','Municipality'],['Pigkawayan','Municipality'],['Pikit','Municipality'],
                ['President Roxas','Municipality'],
            ],
            'SAR' => [
                ['Alabel','Municipality'],['Glan','Municipality'],['Kiamba','Municipality'],
                ['Maasim','Municipality'],['Maitum','Municipality'],['Malapatan','Municipality'],
                ['Malungon','Municipality'],
            ],
            'SCO' => [
                ['Banga','Municipality'],['General Santos City','City'],['Koronadal City','City'],
                ['Lake Sebu','Municipality'],['Norala','Municipality'],['Polomolok','Municipality'],
                ['Santo Niño','Municipality'],['Surallah','Municipality'],["T'Boli",'Municipality'],
                ['Tampakan','Municipality'],['Tantangan','Municipality'],['Tupi','Municipality'],
            ],
            'SKU' => [
                ['Bagumbayan','Municipality'],['Columbio','Municipality'],['Esperanza','Municipality'],
                ['Isulan','Municipality'],['Kalamansig','Municipality'],['Lambayong','Municipality'],
                ['Lebak','Municipality'],['Lutayan','Municipality'],['Palimbang','Municipality'],
                ['President Quirino','Municipality'],['Senator Ninoy Aquino','Municipality'],
                ['Sultan Kudarat','Municipality'],['Tacurong City','City'],
            ],
            'AGN' => [
                ['Buenavista','Municipality'],['Butuan City','City'],['Cabadbaran City','City'],
                ['Carmen','Municipality'],['Jabonga','Municipality'],['Kitcharao','Municipality'],
                ['Las Nieves','Municipality'],['Magallanes','Municipality'],['Nasipit','Municipality'],
                ['Remedios T. Romualdez','Municipality'],['Santiago','Municipality'],['Tubay','Municipality'],
            ],
            'AGS' => [
                ['Bayugan City','City'],['Bunawan','Municipality'],['Esperanza','Municipality'],
                ['La Paz','Municipality'],['Loreto','Municipality'],['Prosperidad','Municipality'],
                ['Rosario','Municipality'],['San Francisco','Municipality'],['San Luis','Municipality'],
                ['Santa Josefa','Municipality'],['Sibagat','Municipality'],['Talacogon','Municipality'],
                ['Trento','Municipality'],['Veruela','Municipality'],
            ],
            'DIN' => [
                ['Basilisa','Municipality'],['Cagdianao','Municipality'],['Dinagat','Municipality'],
                ['Libjo','Municipality'],['Loreto','Municipality'],['San Jose','Municipality'],
                ['Tubajon','Municipality'],
            ],
            'SUN' => [
                ['Alegria','Municipality'],['Bacuag','Municipality'],['Burgos','Municipality'],
                ['Claver','Municipality'],['Dapa','Municipality'],['Del Carmen','Municipality'],
                ['General Luna','Municipality'],['Gigaquit','Municipality'],['Mainit','Municipality'],
                ['Malimono','Municipality'],['Pilar','Municipality'],['Placer','Municipality'],
                ['San Benito','Municipality'],['San Francisco','Municipality'],['San Isidro','Municipality'],
                ['Santa Monica','Municipality'],['Sison','Municipality'],['Socorro','Municipality'],
                ['Surigao City','City'],['Tagana-an','Municipality'],['Tubod','Municipality'],
            ],
            'SUS' => [
                ['Barobo','Municipality'],['Bayabas','Municipality'],['Bislig City','City'],
                ['Cagwait','Municipality'],['Cantilan','Municipality'],['Carmen','Municipality'],
                ['Carrascal','Municipality'],['Cortes','Municipality'],['Hinatuan','Municipality'],
                ['Lanuza','Municipality'],['Lianga','Municipality'],['Lingig','Municipality'],
                ['Madrid','Municipality'],['Marihatag','Municipality'],['San Agustin','Municipality'],
                ['San Miguel','Municipality'],['Tagbina','Municipality'],['Tago','Municipality'],
                ['Tandag City','City'],
            ],
            'BAS' => [
                ['Akbar','Municipality'],['Al-Barka','Municipality'],['Hadji Mohammad Ajul','Municipality'],
                ['Hadji Muhtamad','Municipality'],['Isabela City','City'],['Lamitan City','City'],
                ['Lantawan','Municipality'],['Maluso','Municipality'],['Sumisip','Municipality'],
                ['Tabuan-Lasa','Municipality'],['Tipo-Tipo','Municipality'],['Tuburan','Municipality'],
                ['Ungkaya Pukan','Municipality'],
            ],
            'LDS' => [
                ['Bacolod-Kalawi','Municipality'],['Balabagan','Municipality'],['Balindong','Municipality'],
                ['Bayang','Municipality'],['Binidayan','Municipality'],['Buadiposo-Buntong','Municipality'],
                ['Bubong','Municipality'],['Bumbaran','Municipality'],['Butig','Municipality'],
                ['Calanogas','Municipality'],['Ditsaan-Ramain','Municipality'],['Ganassi','Municipality'],
                ['Kapai','Municipality'],['Kapatagan','Municipality'],['Lumba-Bayabao','Municipality'],
                ['Lumbaca-Unayan','Municipality'],['Lumbatan','Municipality'],['Lumbayanague','Municipality'],
                ['Madalum','Municipality'],['Madamba','Municipality'],['Maguing','Municipality'],
                ['Malabang','Municipality'],['Marantao','Municipality'],['Marawi City','City'],
                ['Marogong','Municipality'],['Masiu','Municipality'],['Mulondo','Municipality'],
                ['Pagayawan','Municipality'],['Piagapo','Municipality'],['Picong','Municipality'],
                ['Poona Bayabao','Municipality'],['Pualas','Municipality'],['Saguiaran','Municipality'],
                ['Sultan Dumalondong','Municipality'],['Sultan Gumander','Municipality'],
                ['Tagoloan II','Municipality'],['Tamparan','Municipality'],['Taraka','Municipality'],
                ['Tubaran','Municipality'],['Tugaya','Municipality'],['Wao','Municipality'],
            ],
            'MGN' => [
                ['Barira','Municipality'],['Buldon','Municipality'],['Datu Blah T. Sinsuat','Municipality'],
                ['Datu Odin Sinsuat','Municipality'],['Kabuntalan','Municipality'],['Matanog','Municipality'],
                ['Northern Kabuntalan','Municipality'],['Parang','Municipality'],
                ['Sultan Kudarat','Municipality'],['Sultan Mastura','Municipality'],['Upi','Municipality'],
            ],
            'MGS' => [
                ['Ampatuan','Municipality'],['Buluan','Municipality'],['Datu Abdullah Sangki','Municipality'],
                ['Datu Anggal Midtimbang','Municipality'],['Datu Hoffer Ampatuan','Municipality'],
                ['Datu Montawal','Municipality'],['Datu Paglas','Municipality'],['Datu Piang','Municipality'],
                ['Datu Salibo','Municipality'],['Datu Saudi-Ampatuan','Municipality'],
                ['Datu Unsay','Municipality'],['Gen. Salipada K. Pendatun','Municipality'],
                ['Guindulungan','Municipality'],['Mamasapano','Municipality'],['Mangudadatu','Municipality'],
                ['Pagagawan','Municipality'],['Paglat','Municipality'],['Pandag','Municipality'],
                ['Rajah Buayan','Municipality'],['Shariff Aguak','Municipality'],
                ['Shariff Saydona Mustapha','Municipality'],['South Upi','Municipality'],
                ['Sultan sa Barongis','Municipality'],['Talayan','Municipality'],['Talitay','Municipality'],
            ],
            'SUL' => [
                ['Hadji Panglima Tahil','Municipality'],['Indanan','Municipality'],['Jolo','Municipality'],
                ['Kalingalan Caluang','Municipality'],['Lugus','Municipality'],['Luuk','Municipality'],
                ['Maimbung','Municipality'],['Marungas','Municipality'],['Old Panamao','Municipality'],
                ['Omar','Municipality'],['Pandami','Municipality'],['Panglima Estino','Municipality'],
                ['Pangutaran','Municipality'],['Parang','Municipality'],['Pata','Municipality'],
                ['Patikul','Municipality'],['Siasi','Municipality'],['Talipao','Municipality'],
                ['Tapul','Municipality'],['Tongkil','Municipality'],
            ],
            'TAW' => [
                ['Balimbing','Municipality'],['Bongao','Municipality'],['Languyan','Municipality'],
                ['Mapun','Municipality'],['Panglima Sugala','Municipality'],['Sapa-Sapa','Municipality'],
                ['Sibutu','Municipality'],['Simunul','Municipality'],['Sitangkai','Municipality'],
                ['South Ubian','Municipality'],['Tandubas','Municipality'],['Turtle Islands','Municipality'],
            ],
        ];
    }
}
